2024-07-04 18:08:03,453 [INFO] root tankworker.py:153	Log file created
2024-07-04 18:08:03,454 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2024-07-04 18:08:03,454 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2024-07-04 18:08:03,454 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2024-07-04 18:08:03,464 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2024-07-04_18-08-03.401657
2024-07-04 18:08:03,466 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2024-07-04 18:08:03,466 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2024-07-04 18:08:03,467 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2024-07-04 18:08:03,467 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2024-07-04 18:08:03,468 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2024-07-04 18:08:03,468 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2024-07-04 18:08:03,469 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2024-07-04 18:08:03,469 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2024-07-04 18:08:03,472 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2024-07-04 18:08:03,472 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2024-07-04 18:08:03,472 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2024-07-04 18:08:03,473 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2024-07-04 18:08:03,473 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2024-07-04 18:08:03,473 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2024-07-04 18:08:03,473 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2024-07-04 18:08:03,474 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2024-07-04 18:08:03,474 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2024-07-04 18:08:03,474 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2024-07-04 18:08:04,516 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 18:08:07,637 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 18:08:07,638 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 18:08:10,756 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 18:08:10,758 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 18:08:11,612 [WARNING] root tankworker.py:118	Interrupting
2024-07-04 18:08:11,616 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'KeyboardInterrupt'>: 
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 579, in resolve
    self.__test(family, (parsed_ip, port))

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 593, in __test
    test_sock.connect(sa)

2024-07-04 18:08:11,616 [INFO] yandextank.common.util util.py:816	Trying to clean up
2024-07-04 18:08:11,617 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_lqz4z8jg.lock
2024-07-04 18:08:11,624 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2024-07-04_18-08-03.401657
2024-07-04 18:08:11,624 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2024-07-04 18:08:11,626 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_18-08-03.401657/answ_6p3d4ht1.log
2024-07-04 18:08:11,627 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_18-08-03.401657/phout_cscb57tp.log
2024-07-04 18:08:11,628 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_18-08-03.401657/phantom_stat_oktlimz0.log
2024-07-04 18:08:11,630 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_18-08-03.401657/phantom_pxuf5b_j.log
