2024-07-04 17:18:58,617 [INFO] root tankworker.py:153	Log file created
2024-07-04 17:18:58,618 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2024-07-04 17:18:58,618 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2024-07-04 17:18:58,618 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2024-07-04 17:18:58,627 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2024-07-04_17-18-58.553343
2024-07-04 17:18:58,629 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2024-07-04 17:18:58,629 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2024-07-04 17:18:58,630 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2024-07-04 17:18:58,630 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2024-07-04 17:18:58,631 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2024-07-04 17:18:58,631 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2024-07-04 17:18:58,631 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2024-07-04 17:18:58,632 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2024-07-04 17:18:58,635 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2024-07-04 17:18:58,636 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2024-07-04 17:18:58,636 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2024-07-04 17:18:58,636 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2024-07-04 17:18:58,637 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2024-07-04 17:18:58,637 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2024-07-04 17:18:58,637 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2024-07-04 17:18:58,637 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2024-07-04 17:18:58,638 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2024-07-04 17:18:58,638 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2024-07-04 17:18:59,670 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:19:02,805 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 17:19:02,805 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:19:05,924 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 17:19:05,925 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:19:07,244 [WARNING] root tankworker.py:118	Interrupting
2024-07-04 17:19:07,246 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'KeyboardInterrupt'>: 
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 579, in resolve
    self.__test(family, (parsed_ip, port))

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 593, in __test
    test_sock.connect(sa)

2024-07-04 17:19:07,249 [INFO] yandextank.common.util util.py:816	Trying to clean up
2024-07-04 17:19:07,251 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_2se26u5q.lock
2024-07-04 17:19:07,270 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2024-07-04_17-18-58.553343
2024-07-04 17:19:07,271 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2024-07-04 17:19:07,274 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-58.553343/answ_nv7oru9j.log
2024-07-04 17:19:07,277 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-58.553343/phout_hmv29lqc.log
2024-07-04 17:19:07,279 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-58.553343/phantom_stat_ol4i5b7b.log
2024-07-04 17:19:07,280 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-18-58.553343/phantom_1sfr4dg_.log
