2024-07-04 17:08:13,529 [INFO] root tankworker.py:153	Log file created
2024-07-04 17:08:13,530 [INFO] root tankworker.py:157	Logging handler <FileHandler /var/loadtest/tank_errors.log (WARNING)> added
2024-07-04 17:08:13,530 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stdout> (INFO)> added
2024-07-04 17:08:13,530 [INFO] root tankworker.py:157	Logging handler <StreamHandler <stderr> (NOTSET)> added
2024-07-04 17:08:13,540 [INFO] root tankworker.py:69	Created a folder for the test. /var/loadtest/logs/2024-07-04_17-08-13.480380
2024-07-04 17:08:13,541 [INFO] yandextank.core.tankcore tankcore.py:254	Configuring plugins...
2024-07-04 17:08:13,541 [INFO] yandextank.core.tankcore tankcore.py:205	Loading plugins...
2024-07-04 17:08:13,542 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: autostop
2024-07-04 17:08:13,542 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Autostop
2024-07-04 17:08:13,543 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: console
2024-07-04 17:08:13,543 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Console
2024-07-04 17:08:13,543 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: json_report
2024-07-04 17:08:13,544 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.JsonReport
2024-07-04 17:08:13,546 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: phantom
2024-07-04 17:08:13,547 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.Phantom
2024-07-04 17:08:13,547 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcheck
2024-07-04 17:08:13,548 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ResourceCheck
2024-07-04 17:08:13,548 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: shellexec
2024-07-04 17:08:13,549 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.ShellExec
2024-07-04 17:08:13,549 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: rcassert
2024-07-04 17:08:13,549 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.RCAssert
2024-07-04 17:08:13,550 [INFO] yandextank.core.tankcore tankcore.py:215	Trying to import module: overload
2024-07-04 17:08:13,550 [INFO] yandextank.core.tankcore tankcore.py:216	Path: yandextank.plugins.DataUploader
2024-07-04 17:08:14,592 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:08:17,731 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 17:08:17,733 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:08:20,846 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 17:08:20,846 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address fdc4:f303:9324::254 and port 5000
2024-07-04 17:08:23,966 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [fdc4:f303:9324::254]:5000
2024-07-04 17:08:23,968 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.254 and port 5000
2024-07-04 17:08:23,975 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.254]:5000
2024-07-04 17:08:23,975 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.254 and port 5000
2024-07-04 17:08:23,977 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.254]:5000
2024-07-04 17:08:23,978 [INFO] yandextank.common.util util.py:578	Testing connection to resolved address 192.168.65.254 and port 5000
2024-07-04 17:08:23,979 [INFO] yandextank.common.util util.py:581	Failed TCP connection test using [192.168.65.254]:5000
2024-07-04 17:08:23,980 [ERROR] yandextank.common.util util.py:815	Exception occurred:
<class 'RuntimeError'>: All connection attempts failed for host.docker.internal, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankworker.py", line 70, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/core/tankcore.py", line 262, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 67, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/plugin.py", line 76, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python3.8/dist-packages/yandextank/plugins/Phantom/utils.py", line 274, in read_config
    self.ipv6, self.resolved_ip, self.port, self.address = self.address_wizard.resolve(

  File "/usr/local/lib/python3.8/dist-packages/yandextank/common/util.py", line 587, in resolve
    raise RuntimeError(msg % address_str)

2024-07-04 17:08:23,980 [INFO] yandextank.common.util util.py:816	Trying to clean up
2024-07-04 17:08:23,981 [INFO] yandextank.core.tankcore tankcore.py:630	Releasing lock: /var/lock/lunapark_z01bedvo.lock
2024-07-04 17:08:23,987 [INFO] yandextank.core.tankcore tankcore.py:405	Artifacts dir: /var/loadtest/logs/2024-07-04_17-08-13.480380
2024-07-04 17:08:23,988 [INFO] yandextank.core.tankcore tankcore.py:461	File not found to collect: validation_error.yaml
2024-07-04 17:08:23,989 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-08-13.480380/answ_bvd22z7o.log
2024-07-04 17:08:23,991 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-08-13.480380/phout_80l7b1kv.log
2024-07-04 17:08:23,992 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-08-13.480380/phantom_stat_pzv3f5io.log
2024-07-04 17:08:23,993 [INFO] yandextank.core.tankcore tankcore.py:466	File already exists: /var/loadtest/logs/2024-07-04_17-08-13.480380/phantom_e99su1j3.log
